language: rust
rust:
- nightly
before_install:
- openssl aes-256-cbc -K $encrypted_f54cdbd2932e_key -iv $encrypted_f54cdbd2932e_iv
  -in .1.env.enc -out .env -d
- openssl aes-256-cbc -K $encrypted_f54cdbd2932e_key -iv $encrypted_f54cdbd2932e_iv
  -in Rusty-random-blog-7db92dab73e8.json.enc -out ~/Rusty-random-blog-7db92dab73e8.json
  -d
deploy:
  provider: gae
  keyfile: "~/Rusty-random-blog-7db92dab73e8.json"
  project: rusty-random-blog-223921
  skip_cleanup: true
