[package]
name = "rust-randomblog"
version = "0.1.0"
authors = ["mairandomness <mairakodama@gmail.com>"]

# bin is the entry point for cargo run and build
[[bin]]
name = "rust-randomblog"
path = "src/bin/main.rs"

# lib the entry point for all main app code
# handles imports, app configuration
[lib]
name = "lil_lib"
path = "src/lib.rs"


[dependencies]
# Server
rocket = "0.3.16"
rocket_codegen = "0.3.16"
rocket_contrib = { version = "0.3.16", default-features = false, features = ["tera_templates"] }

serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.30"
tera = "0.11.3"

# ORM for the database
diesel = { version = "1.3.3", features = ["postgres"] }
diesel_codegen = { version = "0.16", features = ["postgres"] }

# r2d2 - related to database connection pools
r2d2 = "*"
r2d2-diesel = "*"

# SYS
dotenv = "0.10"

